@echo off

echo Installing Mozilla Firefox...
winget install Mozilla.Firefox

echo Installing Microsoft 365 Apps for enterprise...
winget install Microsoft.365

echo Installing PotPlayer...
winget install PotPlayer.PotPlayer

echo Installing VLC media player...
winget install VideoLAN.VLC

echo Installing WinRAR...
winget install RARLab.WinRAR

echo Installing Zotero...
winget install Zotero.Zotero

echo Installing Zoom...
winget install Zoom.Zoom

echo Installing Google Chrome...
winget install Google.Chrome

echo Installing NetSpeedMonitor...
winget install NetSpeedMonitor.NetSpeedMonitor

echo Installing AnyDesk...
winget install AnyDesk.AnyDesk

echo Installing Avro Keyboard...
winget install Avro.Keyboard

echo Installing Brave...
winget install Brave.Brave

echo Installing Internet Download Manager...
winget install Internet.Download.Manager

echo Installing Microsoft Edge...
winget install Microsoft.Edge

echo Installing OBS Studio...
winget install OBSProject.OBSStudio

echo Installing qBittorrent...
winget install qBittorrent.qBittorrent

echo Installing Realtek Audio Driver...
winget install Realtek.Audio.Driver

echo Installing Canva...
winget install Canva.Canva

echo Installing CapCut...
winget install CapCut.CapCut

echo Installing Grammarly for Windows...
winget install Grammarly.Grammarly

echo Installing Microsoft OneDrive...
winget install Microsoft.OneDrive

echo Installing Spotify...
winget install Spotify.Spotify

echo Installing Telegram Desktop...
winget install Telegram.TelegramDesktop

echo Installing Net Monitor...
winget install NetMonitor.NetMonitor

echo Installing WhatsApp...
winget install WhatsApp.WhatsApp

echo Installing Microsoft Photos Legacy...
winget install Microsoft.PhotosLegacy

echo Installing Snipping Tool...
winget install Microsoft.SnippingTool

echo Installation complete!
pause
